cursor                #52676f
selection_foreground  #fcf4dc
selection_background  #52676f

# foreground #657b83
foreground #52676f
background #fdf6e3

# black dark/light
color0                #eee8d5
color8                #fdf6e3

# white dark/light
color7                #073642
color15               #002b36

include solarized-common

#
# cursor  #073642
# cursor_text_color #eee8d5
