cursor                #eee8d6
selection_foreground  #fcf4dc
selection_background  #52676f

foreground #839496
background #002b36


# black dark/light
color0                #073642
color8                #002b36

# white dark/light
color7                #eee8d5
color15               #fdf6e3

include solarized-common

# *borderColor:   S_base03
# *fadeColor:     S_base03
# *pointerColor:  S_base01
# *pointerColor2: S_base1

